# @package _global_

#python lerobot/scripts/train.py \
#    --policy.type=diffusion_stretch_pickup \
#    --dataset.repo_id=lerobot/stretch_pickup \
#    --env.type=stretch_pickup \
#    --output_dir=outputs/train/diffusion_stretch_pickup

fps: 10

env:
  name: stretch_pick
  task: StretchPick-v0
  state_dim: 11 # 11 # base_X, base_Y, base_theta, Lift, Extend, Wrist_yaw, Wrist_pitch, Wrist_roll, Gripper, Head_pan, Head_tilt
  action_dim: 11 #11
  fps: ${fps}
  episode_length: 300
#  gym:
#    obs_type: pixels_agent_pos
#    render_mode: rgb_array
#    visualization_width: 384
#    visualization_height: 384
